# Generated by Django 2.1.7 on 2019-09-28 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('repository', models.URLField()),
                ('healthcheck_url', models.URLField()),
                ('swagger_file_location', models.URLField()),
                ('asyncapi_file_location', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('slack_channel', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='owners',
            field=models.ManyToManyField(to='repository.Team'),
        ),
        migrations.AddField(
            model_name='owner',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Team'),
        ),
    ]
